<?php

namespace ContainerKPI8tI7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NgO3MBaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ngO3MBa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ngO3MBa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employee' => ['privates', '.errored..service_locator.ngO3MBa.App\\Entity\\Employee', NULL, 'Cannot autowire service ".service_locator.ngO3MBa": it needs an instance of "App\\Entity\\Employee" but this type has been excluded in "config/services.yaml".'],
            'projectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'employee' => 'App\\Entity\\Employee',
            'projectRepo' => 'App\\Repository\\ProjectRepository',
            'entityManager' => '?',
        ]);
    }
}
