<?php

namespace ContainerEaIyqs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rj7vJZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rj7v_JZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rj7v_JZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.rj7v_JZ.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.rj7v_JZ": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'empRepo' => ['privates', 'App\\Repository\\EmployeeRepository', 'getEmployeeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'project' => 'App\\Entity\\Project',
            'empRepo' => 'App\\Repository\\EmployeeRepository',
            'entityManager' => '?',
        ]);
    }
}
