<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOThF1Pb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOThF1Pb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOThF1Pb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOThF1Pb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOThF1Pb\App_KernelDevDebugContainer([
    'container.build_hash' => 'OThF1Pb',
    'container.build_id' => 'ab0e569e',
    'container.build_time' => 1737921946,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOThF1Pb');
