<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPI8tI7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPI8tI7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPI8tI7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPI8tI7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKPI8tI7\App_KernelDevDebugContainer([
    'container.build_hash' => 'KPI8tI7',
    'container.build_id' => '27822941',
    'container.build_time' => 1737932606,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPI8tI7');
